/* eslint-disable no-console */
/**
 * Regenerate `src/procedure-types.ts` — the dotted procedure path → kind map the
 * FE's RSC tRPC caller needs to dispatch `.query` vs `.mutation`.
 *
 * The map is a plain literal with zero imports on purpose: importing `appRouter`
 * from a Next server bundle drags the whole backend (better-auth, drizzle, the
 * DB client) into the serverless function. `procedure-types.test.ts` fails if
 * this file drifts from the live router, so a new procedure can't be forgotten.
 *
 *   bun run --cwd packages/api gen:procedure-types
 */
import { appRouter } from "../src/routers/_app";
import { procedureKinds } from "../src/procedure-kinds";

const entries = Object.entries(procedureKinds(appRouter)).sort(([a], [b]) =>
  a.localeCompare(b),
);

const body = entries.map(([path, kind]) => `  "${path}": "${kind}",`).join("\n");

const file = `// GENERATED by scripts/gen-procedure-types.ts — do not edit by hand.
// Run \`bun run --cwd packages/api gen:procedure-types\` after adding a procedure.
//
// Dotted procedure path → kind, as a dependency-free literal so the Next apps'
// RSC tRPC caller can dispatch \`.query\`/\`.mutation\` without importing
// \`appRouter\` (which would pull the entire backend into their bundle).

export type ProcedureKind = "query" | "mutation" | "subscription";

export const PROCEDURE_TYPES: Record<string, ProcedureKind> = {
${body}
};
`;

await Bun.write(new URL("../src/procedure-types.ts", import.meta.url), file);
console.log(`wrote ${entries.length} procedures`);
