// Deploy the PRODUCTION API Worker (`loyalty-api` → api.t4diverclub.app).
//
// Run it under Infisical prod injection so process.env carries the prod secrets
// from `/api` + `/shared` (+ `/ci` for the Cloudflare creds wrangler reads):
//
//   infisical run --env=prod --recursive -- bun scripts/cloudflare/deploy-prod-worker.ts
//
// Mirrors deploy-preview-worker.ts but for the single prod env: no per-PR DB, no
// DNS CNAME upserts (wrangler provisions api.t4diverclub.app via the custom_domain
// route in the generated config), cookie scoped to the bare parent `.t4diverclub.app`,
// and AUTH_PASSWORD_ENABLED=false (Google-only admin in prod — email/password is
// preview/dev only).
//
// Non-secret config → `[vars]` in a generated `wrangler.prod.toml` (gitignored).
// Secrets → `wrangler secret put`, all sourced from Infisical prod (`/api` + `/shared`)
// via `infisical run --env=prod`, which OVERRIDES the shell — so a stale root `.env`
// (e.g. a dev BETTER_AUTH_SECRET) can never shadow a prod value.
import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const ZONE = "t4diverclub.app";
const apiHost = `api.${ZONE}`;
const adminHost = `admin.${ZONE}`;
const webHost = `app.${ZONE}`;

const need = (key: string): string => {
  const value = process.env[key];
  if (!value) {
    throw new Error(
      `${key} is not set — run under: infisical run --env=prod --recursive -- bun scripts/cloudflare/deploy-prod-worker.ts`,
    );
  }
  return value;
};

const accountId = need("CLOUDFLARE_ACCOUNT_ID");
need("CLOUDFLARE_API_TOKEN"); // consumed by wrangler from the environment

// Provider [vars] (non-secret), sourced from Infisical prod. Hard-fail if a
// required one is missing so a half-configured deploy never ships silently.
const partykitHost = need("PARTYKIT_HOST");
const partykitProject = need("PARTYKIT_PROJECT");
const triggerProjectId = need("TRIGGER_PROJECT_ID");
const r2AccountId = need("R2_ACCOUNT_ID");
const r2Bucket = need("R2_BUCKET");
const r2PublicUrl = need("R2_PUBLIC_URL");
const betterStackHost =
  process.env.BETTER_STACK_INGESTING_HOST_API ??
  process.env.BETTER_STACK_INGESTING_HOST ??
  "";

// Guard against accidentally deploying with a dev/shell env (e.g. forgetting the
// `infisical run --env=prod` wrapper) — the localhost party host is the tell.
if (partykitHost.includes("localhost") || partykitHost.includes("127.0.0.1")) {
  throw new Error(
    `PARTYKIT_HOST="${partykitHost}" looks like dev — refusing. Run under infisical run --env=prod --recursive.`,
  );
}

const repoRoot = process.cwd();
const apiDir = join(repoRoot, "apps", "api");
const configPath = join(apiDir, "wrangler.prod.toml");
const wranglerBin = join(repoRoot, "node_modules", ".bin", "wrangler");

// Non-secret config (auth URLs/policy + provider hosts) is `[vars]`; only true
// secrets go through `wrangler secret put` below. Mirrors apps/api/wrangler.toml.
const config = `# generated by scripts/cloudflare/deploy-prod-worker.ts — DO NOT COMMIT
name = "loyalty-api"
main = "src/index.ts"
account_id = "${accountId}"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[observability]
enabled = true

[[routes]]
pattern = "${apiHost}"
custom_domain = true

[vars]
BETTER_AUTH_URL = "https://${apiHost}"
BETTER_AUTH_TRUSTED_ORIGINS = "https://${adminHost},https://${webHost}"
AUTH_COOKIE_DOMAIN = ".${ZONE}"
AUTH_PASSWORD_ENABLED = "false"
SENTRY_ENVIRONMENT = "production"
PARTYKIT_HOST = "${partykitHost}"
PARTYKIT_PROJECT = "${partykitProject}"
TRIGGER_PROJECT_ID = "${triggerProjectId}"
R2_ACCOUNT_ID = "${r2AccountId}"
R2_BUCKET = "${r2Bucket}"
R2_PUBLIC_URL = "${r2PublicUrl}"
${betterStackHost ? `BETTER_STACK_INGESTING_HOST_API = "${betterStackHost}"` : ""}
`;
writeFileSync(configPath, config);

function wrangler(args: string[], input?: string): void {
  const res = spawnSync(wranglerBin, [...args, "-c", configPath], {
    cwd: apiDir,
    env: process.env,
    input,
    stdio: input === undefined ? "inherit" : ["pipe", "inherit", "inherit"],
  });
  if (res.status !== 0) {
    throw new Error(`wrangler ${args.join(" ")} exited ${res.status ?? res.signal}`);
  }
}

console.info(`→ Deploying loyalty-api → https://${apiHost}`);
wrangler(["deploy"]);

// Every secret must exist in Infisical prod (`/api` + `/shared`); `need()` fails
// loudly if any is missing. Injected via `infisical run --env=prod`, which overrides
// the shell, so a stale root `.env` can't shadow a prod value (DB + auth included).
const REQUIRED = [
  "DATABASE_URL",
  "TURSO_AUTH_TOKEN",
  "BETTER_AUTH_SECRET",
  "GOOGLE_CLIENT_ID",
  "GOOGLE_CLIENT_SECRET",
  "REALTIME_AUTH_SECRET",
  "TRIGGER_SECRET_KEY",
  "UPSTASH_REDIS_REST_URL",
  "UPSTASH_REDIS_REST_TOKEN",
  "BETTER_STACK_SOURCE_TOKEN_API",
  "SENTRY_DSN",
  "R2_ACCESS_KEY_ID",
  "R2_SECRET_ACCESS_KEY",
];

for (const key of REQUIRED) {
  const value = need(key);
  console.info(`→ secret put ${key}`);
  wrangler(["secret", "put", key], value);
}

console.info(`✓ loyalty-api deployed → https://${apiHost}`);
console.info(`  trusted origins: https://${adminHost}, https://${webHost}`);
